# Generated by Django 4.1.7 on 2023-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Garagem", "0002_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
