# Generated by Django 4.1.7 on 2023-03-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0004_acessório'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessório',
            new_name='Acessorio',
        ),
    ]
