# Generated by Django 4.1.7 on 2023-03-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0007_alter_acessorio_options_alter_cor_options_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cor',
        ),
    ]
