# Generated by Django 4.1.7 on 2023-03-31 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0008_remove_veiculo_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name_plural': 'Veículo'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculo', to='Garagem.cor'),
        ),
    ]
