# Generated by Django 4.2.4 on 2023-08-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0010_alter_acessorio_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='Acessorio',
            field=models.ManyToManyField(related_name='acessórios', to='Garagem.acessorio'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veículo', to='Garagem.categoria'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veículo', to='Garagem.cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veículo', to='Garagem.marca'),
        ),
    ]
